apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00211
  namespace: sno00211
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00211"
  labels:
    infraenvs.agent-install.openshift.io: "sno00211"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/411d5883-2c5f-4785-9d2c-70af125407c0'
    disableCertificateVerification: true
    credentialsName: sno00211-bmc-secret
  bootMACAddress: '52:54:00:76:0c:07'
  automatedCleaningMode: disabled
  online: true
