apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00239
  namespace: sno00239
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00239"
  labels:
    infraenvs.agent-install.openshift.io: "sno00239"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/eaf6b0af-628c-482f-a74c-aca1d7d08108'
    disableCertificateVerification: true
    credentialsName: sno00239-bmc-secret
  bootMACAddress: '52:54:00:76:0e:01'
  automatedCleaningMode: disabled
  online: true
