apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00291
  namespace: sno00291
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00291"
  labels:
    infraenvs.agent-install.openshift.io: "sno00291"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/4c38cfb9-6bfb-4a73-9754-8a35f1173a28'
    disableCertificateVerification: true
    credentialsName: sno00291-bmc-secret
  bootMACAddress: '52:54:00:76:11:02'
  automatedCleaningMode: disabled
  online: true
