apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00208
  namespace: sno00208
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00208"
  labels:
    infraenvs.agent-install.openshift.io: "sno00208"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/09c3621b-4b92-4b3a-8b65-8c0dc061d759'
    disableCertificateVerification: true
    credentialsName: sno00208-bmc-secret
  bootMACAddress: '52:54:00:76:0c:04'
  automatedCleaningMode: disabled
  online: true
