apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00231
  namespace: sno00231
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00231"
  labels:
    infraenvs.agent-install.openshift.io: "sno00231"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/9695b419-5335-4ebf-b6e7-79546483a5c1'
    disableCertificateVerification: true
    credentialsName: sno00231-bmc-secret
  bootMACAddress: '52:54:00:76:0d:0a'
  automatedCleaningMode: disabled
  online: true
