apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00275
  namespace: sno00275
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00275"
  labels:
    infraenvs.agent-install.openshift.io: "sno00275"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.34:9000/redfish/v1/Systems/a6637a50-127d-407c-97f3-194693e59455'
    disableCertificateVerification: true
    credentialsName: sno00275-bmc-secret
  bootMACAddress: '52:54:00:76:10:03'
  automatedCleaningMode: disabled
  online: true
