apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00272
  namespace: sno00272
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00272"
  labels:
    infraenvs.agent-install.openshift.io: "sno00272"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/482ea911-8462-4ca8-b4de-eca689d0694c'
    disableCertificateVerification: true
    credentialsName: sno00272-bmc-secret
  bootMACAddress: '52:54:00:76:0f:11'
  automatedCleaningMode: disabled
  online: true
