apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00217
  namespace: sno00217
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00217"
  labels:
    infraenvs.agent-install.openshift.io: "sno00217"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/7b3f140c-d361-491a-aecc-329a6701559c'
    disableCertificateVerification: true
    credentialsName: sno00217-bmc-secret
  bootMACAddress: '52:54:00:76:0c:0d'
  automatedCleaningMode: disabled
  online: true
