apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00269
  namespace: sno00269
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00269"
  labels:
    infraenvs.agent-install.openshift.io: "sno00269"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/699bf645-b92c-4159-9f54-f58e2deca83f'
    disableCertificateVerification: true
    credentialsName: sno00269-bmc-secret
  bootMACAddress: '52:54:00:76:0f:0e'
  automatedCleaningMode: disabled
  online: true
