apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00205
  namespace: sno00205
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00205"
  labels:
    infraenvs.agent-install.openshift.io: "sno00205"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/9a605dd1-dd08-4298-94c6-3333b080acb7'
    disableCertificateVerification: true
    credentialsName: sno00205-bmc-secret
  bootMACAddress: '52:54:00:76:0c:01'
  automatedCleaningMode: disabled
  online: true
