apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00228
  namespace: sno00228
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00228"
  labels:
    infraenvs.agent-install.openshift.io: "sno00228"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/1abcc314-a927-40f0-bb15-61ad4d64d634'
    disableCertificateVerification: true
    credentialsName: sno00228-bmc-secret
  bootMACAddress: '52:54:00:76:0d:07'
  automatedCleaningMode: disabled
  online: true
