apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00252
  namespace: sno00252
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00252"
  labels:
    infraenvs.agent-install.openshift.io: "sno00252"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/74f74011-f9f5-4c66-a5ba-c8141ae79434'
    disableCertificateVerification: true
    credentialsName: sno00252-bmc-secret
  bootMACAddress: '52:54:00:76:0e:0e'
  automatedCleaningMode: disabled
  online: true
