apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00253
  namespace: sno00253
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00253"
  labels:
    infraenvs.agent-install.openshift.io: "sno00253"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/b39d92c9-9f3f-47d9-bdb9-b3f8102fd759'
    disableCertificateVerification: true
    credentialsName: sno00253-bmc-secret
  bootMACAddress: '52:54:00:76:0e:0f'
  automatedCleaningMode: disabled
  online: true
