apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00297
  namespace: sno00297
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00297"
  labels:
    infraenvs.agent-install.openshift.io: "sno00297"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/4da4715b-3376-49fc-801c-65b0a1583d11'
    disableCertificateVerification: true
    credentialsName: sno00297-bmc-secret
  bootMACAddress: '52:54:00:76:11:08'
  automatedCleaningMode: disabled
  online: true
