apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00236
  namespace: sno00236
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00236"
  labels:
    infraenvs.agent-install.openshift.io: "sno00236"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/e9cd44c2-8e97-4490-bb24-843ef0b8e75d'
    disableCertificateVerification: true
    credentialsName: sno00236-bmc-secret
  bootMACAddress: '52:54:00:76:0d:0f'
  automatedCleaningMode: disabled
  online: true
