apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00214
  namespace: sno00214
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00214"
  labels:
    infraenvs.agent-install.openshift.io: "sno00214"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/af027342-6676-4709-a2fa-b8bf287cb8ac'
    disableCertificateVerification: true
    credentialsName: sno00214-bmc-secret
  bootMACAddress: '52:54:00:76:0c:0a'
  automatedCleaningMode: disabled
  online: true
