apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00249
  namespace: sno00249
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00249"
  labels:
    infraenvs.agent-install.openshift.io: "sno00249"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/265f42d8-7401-4d39-981a-4080821f1d98'
    disableCertificateVerification: true
    credentialsName: sno00249-bmc-secret
  bootMACAddress: '52:54:00:76:0e:0b'
  automatedCleaningMode: disabled
  online: true
