apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00246
  namespace: sno00246
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00246"
  labels:
    infraenvs.agent-install.openshift.io: "sno00246"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/4364a9f4-a18e-4a2a-a18b-a06991e7d566'
    disableCertificateVerification: true
    credentialsName: sno00246-bmc-secret
  bootMACAddress: '52:54:00:76:0e:08'
  automatedCleaningMode: disabled
  online: true
