apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00264
  namespace: sno00264
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00264"
  labels:
    infraenvs.agent-install.openshift.io: "sno00264"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/cf4eb787-c681-45d7-b592-a4346039592e'
    disableCertificateVerification: true
    credentialsName: sno00264-bmc-secret
  bootMACAddress: '52:54:00:76:0f:09'
  automatedCleaningMode: disabled
  online: true
