apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00235
  namespace: sno00235
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00235"
  labels:
    infraenvs.agent-install.openshift.io: "sno00235"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/54a9a074-dd33-4345-90b6-b460486a5635'
    disableCertificateVerification: true
    credentialsName: sno00235-bmc-secret
  bootMACAddress: '52:54:00:76:0d:0e'
  automatedCleaningMode: disabled
  online: true
