apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00289
  namespace: sno00289
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00289"
  labels:
    infraenvs.agent-install.openshift.io: "sno00289"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.34:9000/redfish/v1/Systems/af362e62-7c1c-46fa-ac52-033d3f259955'
    disableCertificateVerification: true
    credentialsName: sno00289-bmc-secret
  bootMACAddress: '52:54:00:76:10:11'
  automatedCleaningMode: disabled
  online: true
