apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00209
  namespace: sno00209
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00209"
  labels:
    infraenvs.agent-install.openshift.io: "sno00209"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/b4c72313-099d-4a45-a7dc-afc6d7e72e3f'
    disableCertificateVerification: true
    credentialsName: sno00209-bmc-secret
  bootMACAddress: '52:54:00:76:0c:05'
  automatedCleaningMode: disabled
  online: true
