apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00267
  namespace: sno00267
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00267"
  labels:
    infraenvs.agent-install.openshift.io: "sno00267"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/d60a33ac-3d8f-4e6d-a60d-457fc1a497e3'
    disableCertificateVerification: true
    credentialsName: sno00267-bmc-secret
  bootMACAddress: '52:54:00:76:0f:0c'
  automatedCleaningMode: disabled
  online: true
