apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00200
  namespace: sno00200
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00200"
  labels:
    infraenvs.agent-install.openshift.io: "sno00200"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/ce4c93f9-6c20-404c-8f67-34e3ac2063de'
    disableCertificateVerification: true
    credentialsName: sno00200-bmc-secret
  bootMACAddress: '52:54:00:76:0b:0d'
  automatedCleaningMode: disabled
  online: true
