apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00219
  namespace: sno00219
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00219"
  labels:
    infraenvs.agent-install.openshift.io: "sno00219"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/0597bd90-fa4b-47ae-a68d-187a21385997'
    disableCertificateVerification: true
    credentialsName: sno00219-bmc-secret
  bootMACAddress: '52:54:00:76:0c:0f'
  automatedCleaningMode: disabled
  online: true
