apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00287
  namespace: sno00287
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00287"
  labels:
    infraenvs.agent-install.openshift.io: "sno00287"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.34:9000/redfish/v1/Systems/ecee58cd-4ac2-453f-83ea-ef917291a8a4'
    disableCertificateVerification: true
    credentialsName: sno00287-bmc-secret
  bootMACAddress: '52:54:00:76:10:0f'
  automatedCleaningMode: disabled
  online: true
