apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00257
  namespace: sno00257
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00257"
  labels:
    infraenvs.agent-install.openshift.io: "sno00257"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/f25bccf8-7b42-46fc-874c-7b4fd8698a4c'
    disableCertificateVerification: true
    credentialsName: sno00257-bmc-secret
  bootMACAddress: '52:54:00:76:0f:02'
  automatedCleaningMode: disabled
  online: true
