apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00290
  namespace: sno00290
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00290"
  labels:
    infraenvs.agent-install.openshift.io: "sno00290"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/2c9fc760-16b3-4f9c-9946-53c8b4930a0c'
    disableCertificateVerification: true
    credentialsName: sno00290-bmc-secret
  bootMACAddress: '52:54:00:76:11:01'
  automatedCleaningMode: disabled
  online: true
