apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00266
  namespace: sno00266
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00266"
  labels:
    infraenvs.agent-install.openshift.io: "sno00266"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.33:9000/redfish/v1/Systems/80c1059d-cb55-40c7-94e9-d9ddd51f9a77'
    disableCertificateVerification: true
    credentialsName: sno00266-bmc-secret
  bootMACAddress: '52:54:00:76:0f:0b'
  automatedCleaningMode: disabled
  online: true
