apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00233
  namespace: sno00233
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00233"
  labels:
    infraenvs.agent-install.openshift.io: "sno00233"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/db5dd682-bc05-4d29-8c63-9578510fbdb8'
    disableCertificateVerification: true
    credentialsName: sno00233-bmc-secret
  bootMACAddress: '52:54:00:76:0d:0c'
  automatedCleaningMode: disabled
  online: true
