apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00201
  namespace: sno00201
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00201"
  labels:
    infraenvs.agent-install.openshift.io: "sno00201"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/5c556f09-fcb7-4d5d-b512-9a90698927dc'
    disableCertificateVerification: true
    credentialsName: sno00201-bmc-secret
  bootMACAddress: '52:54:00:76:0b:0e'
  automatedCleaningMode: disabled
  online: true
