apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00230
  namespace: sno00230
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00230"
  labels:
    infraenvs.agent-install.openshift.io: "sno00230"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/e5c9fef1-e398-419a-9b7a-571bf0cc8b75'
    disableCertificateVerification: true
    credentialsName: sno00230-bmc-secret
  bootMACAddress: '52:54:00:76:0d:09'
  automatedCleaningMode: disabled
  online: true
