apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00247
  namespace: sno00247
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00247"
  labels:
    infraenvs.agent-install.openshift.io: "sno00247"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/882ef766-c55d-4f52-876a-6043ea96f41a'
    disableCertificateVerification: true
    credentialsName: sno00247-bmc-secret
  bootMACAddress: '52:54:00:76:0e:09'
  automatedCleaningMode: disabled
  online: true
