apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00243
  namespace: sno00243
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00243"
  labels:
    infraenvs.agent-install.openshift.io: "sno00243"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.32:9000/redfish/v1/Systems/29c12dce-15ae-4e4f-b391-bfbb34b2b5af'
    disableCertificateVerification: true
    credentialsName: sno00243-bmc-secret
  bootMACAddress: '52:54:00:76:0e:05'
  automatedCleaningMode: disabled
  online: true
