apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00234
  namespace: sno00234
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00234"
  labels:
    infraenvs.agent-install.openshift.io: "sno00234"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.31:9000/redfish/v1/Systems/9ad3c2fe-4dda-4339-8fa5-9a8b7dd04948'
    disableCertificateVerification: true
    credentialsName: sno00234-bmc-secret
  bootMACAddress: '52:54:00:76:0d:0d'
  automatedCleaningMode: disabled
  online: true
