apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00218
  namespace: sno00218
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00218"
  labels:
    infraenvs.agent-install.openshift.io: "sno00218"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/d4bcf964-8663-4f8a-b58c-a73fd0d663f1'
    disableCertificateVerification: true
    credentialsName: sno00218-bmc-secret
  bootMACAddress: '52:54:00:76:0c:0e'
  automatedCleaningMode: disabled
  online: true
