apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00206
  namespace: sno00206
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00206"
  labels:
    infraenvs.agent-install.openshift.io: "sno00206"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.30:9000/redfish/v1/Systems/c263a04e-399d-49fc-9e1d-545943cbe8dd'
    disableCertificateVerification: true
    credentialsName: sno00206-bmc-secret
  bootMACAddress: '52:54:00:76:0c:02'
  automatedCleaningMode: disabled
  online: true
