apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00204
  namespace: sno00204
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00204"
  labels:
    infraenvs.agent-install.openshift.io: "sno00204"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/f7e5ffe6-d9d4-4966-92c9-b57cbde41ade'
    disableCertificateVerification: true
    credentialsName: sno00204-bmc-secret
  bootMACAddress: '52:54:00:76:0b:11'
  automatedCleaningMode: disabled
  online: true
